CREATE DATABASE IF NOT EXISTS TwoGs;

Use TwoGs;


CREATE TABLE IF NOT EXISTS "Estadisticas" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"KDA"	INTEGER NOT NULL,
	"Asesinatos"	INTEGER NOT NULL,
	"Muertes"	INTEGER NOT NULL,
	"Asistencias"	INTEGER NOT NULL,
	"Partidos-jugados"	INTEGER NOT NULL,
	"ID-Jugador"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);